package domain;

// Generated 4 nov. 2015 13:38:10 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Categoryproduct generated by hbm2java
 */
@Entity
@Table(name = "categoryproduct", schema = "public")
public class Categoryproduct implements java.io.Serializable {

	private short categoryId;
	private Categoryproduct categoryproduct;
	private String categoryLabel;
	private Set products = new HashSet(0);
	private Set categoryproducts = new HashSet(0);

	public Categoryproduct() {
	}

	public Categoryproduct(short categoryId, Categoryproduct categoryproduct) {
		this.categoryId = categoryId;
		this.categoryproduct = categoryproduct;
	}

	public Categoryproduct(short categoryId, Categoryproduct categoryproduct,
			String categoryLabel, Set products, Set categoryproducts) {
		this.categoryId = categoryId;
		this.categoryproduct = categoryproduct;
		this.categoryLabel = categoryLabel;
		this.products = products;
		this.categoryproducts = categoryproducts;
	}

	@Id
	@Column(name = "category_id", unique = true, nullable = false)
	@SequenceGenerator(name="catProductIdSeq", sequenceName="public.category_product_id_seq")
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="catProductIdSeq")
	public short getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(short categoryId) {
		this.categoryId = categoryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_parent_id", nullable = false)
	public Categoryproduct getCategoryproduct() {
		return this.categoryproduct;
	}

	public void setCategoryproduct(Categoryproduct categoryproduct) {
		this.categoryproduct = categoryproduct;
	}

	@Column(name = "category_label", length = 50)
	public String getCategoryLabel() {
		return this.categoryLabel;
	}

	public void setCategoryLabel(String categoryLabel) {
		this.categoryLabel = categoryLabel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoryproduct")
	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoryproduct")
	public Set getCategoryproducts() {
		return this.categoryproducts;
	}

	public void setCategoryproducts(Set categoryproducts) {
		this.categoryproducts = categoryproducts;
	}

}
