package domain;

// Generated 9 nov. 2015 19:47:09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Cotisation generated by hbm2java
 */
@Entity
@Table(name = "cotisation", schema = "public")
@XmlRootElement	(name ="cotisation")
public class Cotisation implements java.io.Serializable {

	private short cotisationId;
	private Formule formule;
	private User user;
	private Date orderDate;

	public Cotisation() {
	}

	public Cotisation(short cotisationId, Formule formule, User user,
			Date orderDate) {
		this.cotisationId = cotisationId;
		this.formule = formule;
		this.user = user;
		this.orderDate = orderDate;
	}

	@Id
	@Column(name = "cotisation_id", unique = true, nullable = false)
	@SequenceGenerator(name="cotisationIdSeq", sequenceName="public.cotisation_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="cotisationIdSeq")
	public short getCotisationId() {
		return this.cotisationId;
	}

	public void setCotisationId(short cotisationId) {
		this.cotisationId = cotisationId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "formule_id", nullable = false)
	public Formule getFormule() {
		return this.formule;
	}

	public void setFormule(Formule formule) {
		this.formule = formule;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "member_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "order_date", nullable = false, length = 13)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

}
