package domain;

// Generated 4 nov. 2015 13:38:10 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cotisation generated by hbm2java
 */
@Entity
@Table(name = "cotisation", schema = "public")
public class Cotisation implements java.io.Serializable {

	private short cotisationId;
	private Formule formule;
	private User User;
	private Date orderDate;

	public Cotisation() {
	}

	public Cotisation(short cotisationId, Formule formule,
			User User, Date orderDate) {
		this.cotisationId = cotisationId;
		this.formule = formule;
		this.User = User;
		this.orderDate = orderDate;
	}

	@Id
	@Column(name = "cotisation_id", unique = true, nullable = false)
	public short getCotisationId() {
		return this.cotisationId;
	}

	public void setCotisationId(short cotisationId) {
		this.cotisationId = cotisationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "formule_id", nullable = false)
	public Formule getFormule() {
		return this.formule;
	}

	public void setFormule(Formule formule) {
		this.formule = formule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id", nullable = false)
	public User getUser() {
		return this.User;
	}

	public void setUser(User User) {
		this.User = User;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "order_date", nullable = false, length = 13)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

}
