package domain;

// Generated 9 nov. 2015 19:47:09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ExcludeddateId generated by hbm2java
 */
@Embeddable
public class ExcludeddateId implements java.io.Serializable {

	private Date excludedDate;
	private short eventId;

	public ExcludeddateId() {
	}

	public ExcludeddateId(Date excludedDate, short eventId) {
		this.excludedDate = excludedDate;
		this.eventId = eventId;
	}

	@Column(name = "excluded_date", nullable = false, length = 13)
	public Date getExcludedDate() {
		return this.excludedDate;
	}

	public void setExcludedDate(Date excludedDate) {
		this.excludedDate = excludedDate;
	}

	@Column(name = "event_id", nullable = false)
	public short getEventId() {
		return this.eventId;
	}

	public void setEventId(short eventId) {
		this.eventId = eventId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ExcludeddateId))
			return false;
		ExcludeddateId castOther = (ExcludeddateId) other;

		return ((this.getExcludedDate() == castOther.getExcludedDate()) || (this
				.getExcludedDate() != null
				&& castOther.getExcludedDate() != null && this
				.getExcludedDate().equals(castOther.getExcludedDate())))
				&& (this.getEventId() == castOther.getEventId());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getExcludedDate() == null ? 0 : this.getExcludedDate()
						.hashCode());
		result = 37 * result + this.getEventId();
		return result;
	}

}
