package domain;

// Generated 4 nov. 2015 13:38:10 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Excludeddate generated by hbm2java
 */
@Entity
@Table(name = "excludeddate", schema = "public")
public class Excludeddate implements java.io.Serializable {

	private ExcludeddateId id;
	private Event event;

	public Excludeddate() {
	}

	public Excludeddate(ExcludeddateId id, Event event) {
		this.id = id;
		this.event = event;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "excludedDate", column = @Column(name = "excluded_date", nullable = false, length = 13)),
			@AttributeOverride(name = "eventId", column = @Column(name = "event_id", nullable = false)) })
	public ExcludeddateId getId() {
		return this.id;
	}

	public void setId(ExcludeddateId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "event_id", nullable = false, insertable = false, updatable = false)
	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

}
