package domain;

// Generated 4 nov. 2015 13:38:10 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Formule generated by hbm2java
 */
@Entity
@Table(name = "formule", schema = "public")
public class Formule implements java.io.Serializable {

	private short formuleId;
	private String formuleLabel;
	private Set cotisations = new HashSet(0);

	public Formule() {
	}

	public Formule(short formuleId) {
		this.formuleId = formuleId;
	}

	public Formule(short formuleId, String formuleLabel, Set cotisations) {
		this.formuleId = formuleId;
		this.formuleLabel = formuleLabel;
		this.cotisations = cotisations;
	}

	@Id
	@Column(name = "formule_id", unique = true, nullable = false)
	public short getFormuleId() {
		return this.formuleId;
	}

	public void setFormuleId(short formuleId) {
		this.formuleId = formuleId;
	}

	@Column(name = "formule_label", length = 50)
	public String getFormuleLabel() {
		return this.formuleLabel;
	}

	public void setFormuleLabel(String formuleLabel) {
		this.formuleLabel = formuleLabel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formule")
	public Set getCotisations() {
		return this.cotisations;
	}

	public void setCotisations(Set cotisations) {
		this.cotisations = cotisations;
	}

}
