package domain;

// Generated 9 nov. 2015 19:47:09 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Formule generated by hbm2java
 */
@Entity
@Table(name = "formule", schema = "public")
@XmlRootElement	(name ="formule")
public class Formule implements java.io.Serializable {

	private short formuleId;
	private String formuleLabel;
	private Set<Cotisation> cotisations = new HashSet<Cotisation>(0);

	public Formule() {
	}

	public Formule(short formuleId) {
		this.formuleId = formuleId;
	}

	public Formule(short formuleId, String formuleLabel,
			Set<Cotisation> cotisations) {
		this.formuleId = formuleId;
		this.formuleLabel = formuleLabel;
		this.cotisations = cotisations;
	}

	@Id
	@Column(name = "formule_id", unique = true, nullable = false)
	@SequenceGenerator(name="formuleIdSeq", sequenceName="public.formule_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="formuleIdSeq")
	public short getFormuleId() {
		return this.formuleId;
	}

	public void setFormuleId(short formuleId) {
		this.formuleId = formuleId;
	}

	@Column(name = "formule_label", length = 50)
	public String getFormuleLabel() {
		return this.formuleLabel;
	}

	public void setFormuleLabel(String formuleLabel) {
		this.formuleLabel = formuleLabel;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "formule")
	public Set<Cotisation> getCotisations() {
		return this.cotisations;
	}

	public void setCotisations(Set<Cotisation> cotisations) {
		this.cotisations = cotisations;
	}

}
