package domain;

// Generated 9 nov. 2015 19:47:09 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * InscriptionId generated by hbm2java
 */
@Embeddable
@XmlRootElement	(name ="inscriptionId")
public class InscriptionId implements java.io.Serializable {

	private short memberId;
	private short eventId;

	public InscriptionId() {
	}

	public InscriptionId(short memberId, short eventId) {
		this.memberId = memberId;
		this.eventId = eventId;
	}

	@Column(name = "member_id", nullable = false)
	public short getMemberId() {
		return this.memberId;
	}

	public void setMemberId(short memberId) {
		this.memberId = memberId;
	}

	@Column(name = "event_id", nullable = false)
	public short getEventId() {
		return this.eventId;
	}

	public void setEventId(short eventId) {
		this.eventId = eventId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InscriptionId))
			return false;
		InscriptionId castOther = (InscriptionId) other;

		return (this.getMemberId() == castOther.getMemberId())
				&& (this.getEventId() == castOther.getEventId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMemberId();
		result = 37 * result + this.getEventId();
		return result;
	}

}
