package domain;

// Generated 4 nov. 2015 13:38:10 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Notification generated by hbm2java
 */
@Entity
@Table(name = "notification", schema = "public")
public class Notification implements java.io.Serializable {

	private short notificationId;
	private ZerenetyUser zerenetyUser;
	private boolean isRead;
	private boolean isCreationDemand;

	public Notification() {
	}

	public Notification(short notificationId, ZerenetyUser zerenetyUser,
			boolean isRead, boolean isCreationDemand) {
		this.notificationId = notificationId;
		this.zerenetyUser = zerenetyUser;
		this.isRead = isRead;
		this.isCreationDemand = isCreationDemand;
	}

	@Id
	@Column(name = "notification_id", unique = true, nullable = false)
	public short getNotificationId() {
		return this.notificationId;
	}

	public void setNotificationId(short notificationId) {
		this.notificationId = notificationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "receiver", nullable = false)
	public ZerenetyUser getZerenetyUser() {
		return this.zerenetyUser;
	}

	public void setZerenetyUser(ZerenetyUser zerenetyUser) {
		this.zerenetyUser = zerenetyUser;
	}

	@Column(name = "is_read", nullable = false)
	public boolean isIsRead() {
		return this.isRead;
	}

	public void setIsRead(boolean isRead) {
		this.isRead = isRead;
	}

	@Column(name = "is_creation_demand", nullable = false)
	public boolean isIsCreationDemand() {
		return this.isCreationDemand;
	}

	public void setIsCreationDemand(boolean isCreationDemand) {
		this.isCreationDemand = isCreationDemand;
	}

}
