package domain;

// Generated 4 nov. 2015 13:38:10 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", schema = "public")
public class Product implements java.io.Serializable {

	private short productId;
	private Categoryproduct categoryproduct;
	private double productPrice;
	private int stockQuantity;
	private Set orderlines = new HashSet(0);

	public Product() {
	}

	public Product(short productId, Categoryproduct categoryproduct,
			double productPrice, int stockQuantity) {
		this.productId = productId;
		this.categoryproduct = categoryproduct;
		this.productPrice = productPrice;
		this.stockQuantity = stockQuantity;
	}

	public Product(short productId, Categoryproduct categoryproduct,
			double productPrice, int stockQuantity, Set orderlines) {
		this.productId = productId;
		this.categoryproduct = categoryproduct;
		this.productPrice = productPrice;
		this.stockQuantity = stockQuantity;
		this.orderlines = orderlines;
	}

	@Id
	@Column(name = "product_id", unique = true, nullable = false)
	public short getProductId() {
		return this.productId;
	}

	public void setProductId(short productId) {
		this.productId = productId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public Categoryproduct getCategoryproduct() {
		return this.categoryproduct;
	}

	public void setCategoryproduct(Categoryproduct categoryproduct) {
		this.categoryproduct = categoryproduct;
	}

	@Column(name = "product_price", nullable = false, precision = 17, scale = 17)
	public double getProductPrice() {
		return this.productPrice;
	}

	public void setProductPrice(double productPrice) {
		this.productPrice = productPrice;
	}

	@Column(name = "stock_quantity", nullable = false)
	public int getStockQuantity() {
		return this.stockQuantity;
	}

	public void setStockQuantity(int stockQuantity) {
		this.stockQuantity = stockQuantity;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set getOrderlines() {
		return this.orderlines;
	}

	public void setOrderlines(Set orderlines) {
		this.orderlines = orderlines;
	}

}
