package domain;

// Generated 4 nov. 2015 13:38:10 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Repetition generated by hbm2java
 */
@Entity
@Table(name = "repetition", schema = "public")
public class Repetition implements java.io.Serializable {

	private short repetitionId;
	private String repetitionLabel;
	private Set events = new HashSet(0);

	public Repetition() {
	}

	public Repetition(short repetitionId) {
		this.repetitionId = repetitionId;
	}

	public Repetition(short repetitionId, String repetitionLabel, Set events) {
		this.repetitionId = repetitionId;
		this.repetitionLabel = repetitionLabel;
		this.events = events;
	}

	@Id
	@Column(name = "repetition_id", unique = true, nullable = false)
	public short getRepetitionId() {
		return this.repetitionId;
	}

	public void setRepetitionId(short repetitionId) {
		this.repetitionId = repetitionId;
	}

	@Column(name = "repetition_label", length = 50)
	public String getRepetitionLabel() {
		return this.repetitionLabel;
	}

	public void setRepetitionLabel(String repetitionLabel) {
		this.repetitionLabel = repetitionLabel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "repetition")
	public Set getEvents() {
		return this.events;
	}

	public void setEvents(Set events) {
		this.events = events;
	}

}
