package domain;

// Generated 9 nov. 2015 19:47:09 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Repetition generated by hbm2java
 */
@Entity
@Table(name = "repetition", schema = "public")
@XmlRootElement	(name ="repetition")
public class Repetition implements java.io.Serializable {

	private short repetitionId;
	private String repetitionLabel;
	private Set<Event> events = new HashSet<Event>(0);

	public Repetition() {
	}

	public Repetition(short repetitionId) {
		this.repetitionId = repetitionId;
	}

	public Repetition(short repetitionId, String repetitionLabel,
			Set<Event> events) {
		this.repetitionId = repetitionId;
		this.repetitionLabel = repetitionLabel;
		this.events = events;
	}

	@Id
	@Column(name = "repetition_id", unique = true, nullable = false)
	@SequenceGenerator(name="repetitionIdSeq", sequenceName="public.repetition_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="repetitionIdSeq")
	public short getRepetitionId() {
		return this.repetitionId;
	}

	public void setRepetitionId(short repetitionId) {
		this.repetitionId = repetitionId;
	}

	@Column(name = "repetition_label", length = 50)
	public String getRepetitionLabel() {
		return this.repetitionLabel;
	}

	public void setRepetitionLabel(String repetitionLabel) {
		this.repetitionLabel = repetitionLabel;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "repetition")
	public Set<Event> getEvents() {
		return this.events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}

}
