package domain;

// Generated 9 nov. 2015 19:47:09 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Room generated by hbm2java
 */
@Entity
@Table(name = "room", schema = "public")
@XmlRootElement	(name ="room")
public class Room implements java.io.Serializable {

	private short roomId;
	private String roomArea;
	private String roomType;
	private Short capacity;
	private Set<Event> events = new HashSet<Event>(0);

	public Room() {
	}

	public Room(short roomId) {
		this.roomId = roomId;
	}

	public Room(short roomId, String roomArea, String roomType, Short capacity,
			Set<Event> events) {
		this.roomId = roomId;
		this.roomArea = roomArea;
		this.roomType = roomType;
		this.capacity = capacity;
		this.events = events;
	}

	@Id
	@Column(name = "room_id", unique = true, nullable = false)
	@SequenceGenerator(name="roomIdSeq", sequenceName="public.room_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="roomIdSeq")
	public short getRoomId() {
		return this.roomId;
	}

	public void setRoomId(short roomId) {
		this.roomId = roomId;
	}

	@Column(name = "room_area", length = 50)
	public String getRoomArea() {
		return this.roomArea;
	}

	public void setRoomArea(String roomArea) {
		this.roomArea = roomArea;
	}

	@Column(name = "room_type", length = 25)
	public String getRoomType() {
		return this.roomType;
	}

	public void setRoomType(String roomType) {
		this.roomType = roomType;
	}

	@Column(name = "capacity")
	public short getCapacity() {
		return this.capacity;
	}

	public void setCapacity(short capacity) {
		this.capacity = capacity;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "room")
	public Set<Event> getEvents() {
		return this.events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}

}
