package domain;

// Generated 4 nov. 2015 13:38:10 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Userorder generated by hbm2java
 */
@Entity
@Table(name = "userorder", schema = "public")
public class Userorder implements java.io.Serializable {

	private short orderId;
	private ZerenetyUser zerenetyUser;
	private Date orderDate;
	private Set orderlines = new HashSet(0);

	public Userorder() {
	}

	public Userorder(short orderId, ZerenetyUser zerenetyUser, Date orderDate) {
		this.orderId = orderId;
		this.zerenetyUser = zerenetyUser;
		this.orderDate = orderDate;
	}

	public Userorder(short orderId, ZerenetyUser zerenetyUser, Date orderDate,
			Set orderlines) {
		this.orderId = orderId;
		this.zerenetyUser = zerenetyUser;
		this.orderDate = orderDate;
		this.orderlines = orderlines;
	}

	@Id
	@Column(name = "order_id", unique = true, nullable = false)
	public short getOrderId() {
		return this.orderId;
	}

	public void setOrderId(short orderId) {
		this.orderId = orderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public ZerenetyUser getZerenetyUser() {
		return this.zerenetyUser;
	}

	public void setZerenetyUser(ZerenetyUser zerenetyUser) {
		this.zerenetyUser = zerenetyUser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "order_date", nullable = false, length = 13)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userorder")
	public Set getOrderlines() {
		return this.orderlines;
	}

	public void setOrderlines(Set orderlines) {
		this.orderlines = orderlines;
	}

}
